var wvy = wvy || {};
wvy.resources = {
"+add an option": "agregar una opción",
"Add meeting": "agregar una reunión",
"Add poll": "",
"Align center": "alinear al centro",
"Align left": "alinear a la izquierda",
"Align right": "alinear a la derecha",
"and": "y",
"are typing": "esta escribiendo",
"Are you sure you want to leave this page? There are some unsaved changes.": "¿Seguro de dejar la página? Existen cambios sin guardar.",
"Attachment was restored.": "adjunto fue restaurado",
"Attachment was trashed.": "adjunto fue borrado",
"Authentication error.": "error de autenticación",
"Browser does not support notifications": "Explorador no soporta notificaciones",
"Close": "Cerrar",
"Comment was restored.": "Comentario fue restuarado",
"Comment was trashed.": "Comentario fue eliminado",
"Follow": "Seguir",
"Following": "Siguiendo",
"Heading 1": "Encabezado 1",
"Heading 2": "Encabezado 2",
"Heading 3": "Encabezado 3",
"Heading 4": "Encabezado 4",
"Heading 5": "Encabezado 5",
"Heading 6": "Encabezado 6",
"Heading 9": "Encabezado 9",
"Hide completed": "Mostrar menos",
"Insert emoji": "Insertar emoji",
"Insert file": "Insertar archivo",
"Insert image": "Insertar imagen",
"Insert/edit file": "Insertar/editar archivo",
"Insert/edit image": "Insertar/editar imagen",
"Insert/edit link": "Insertar/editar link",
"invite": "invitar",
"is typing": "esta escribiendo",
"Justify": "justificar",
"Keyboard shortcuts": "Atajos de teclado",
"Mark as read": "Marcar como leido",
"Mark as unread": "Marcar como no leido",
"Message from": "Mensaje de",
"More": "Más",
"Normal text": "Texto normal",
"Please sign in to the meeting provider before you submit the comment!": "Please sign in to the meeting provider before you submit the comment!",
"Please sign in to the meeting provider before you submit the message!": "Please sign in to the meeting provider before you submit the message!",
"Please sign in to the meeting provider before you submit the post!": "Please sign in to the meeting provider before you submit the post!",
"Post was restored.": "Post fue restaurado",
"Post was trashed.": "Post fue eliminado",
"Reconnecting...": "Reconectando",
"Reload": "Recargar",
"Remove": "Remover",
"Remove format": "Remover formato",
"Saved": "Grabado",
"Saving": "Grabando",
"Search...": "Buscar...",
"Show completed": "Mostrar todo",
"Source code": "Source code",
"Star": "Favorito",
"Strikethrough": "",
"Submit": "",
"Task details": "Task details",
"Task was restored.": "Task was restored.",
"Task was trashed.": "Task was trashed",
"Teams meeting": "Teams meeting",
"The item was deleted.": "The item was deleted.",
"The item was restored.": "The item was restored",
"The signed in user has changed.": "The signed in user has changed",
"Toggle bulleted list": "Toggle bulleted list",
"Toggle numbered list": "Toggle numbered list",
"Toggle toolbar": "Toggle toolbar",
"Undo": "Deshacer",
"Unfollow": "Dejar de Seguir",
"Unstar": "Quitar de Favoritos",
"User was restored.": "Usuario fue restaurado",
"User was trashed.": "Usuario fue borrado",
"What's on your mind?": "¿En que estás pendando?",
"You have a new notification": "Tienes una nueva notificación",
"You have been signed out.": "Has cerrado la sesión",
"You have signed in.": "Tu has iniciado sesión",
"Your comment...": "Tus comentarios...",
"Zoom meeting": "Reunión Zoom",
};
