# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Crecer.Fair.Api.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  publishFolder: 'deploy'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'


- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c release -o $(publishFolder) --no-restore'
    zipAfterPublish: false
- task: BeanstalkDeployApplication@1
  inputs:
    regionName: 'us-west-2'
    applicationName: 'Crecer.Fair.Api'
    environmentName: 'Crecerfairapi-env'
    applicationType: 'aspnetCoreWindows'
    dotnetPublishPath: $(publishFolder)